<a href="https://colab.research.google.com/github/yulissajimenez-10/Continua2-curso-DSW2/blob/master/el_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [9]:
lista = [1,2,3,4,5,6,7,8,9]
lista   

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [11]:
arr = np.array(lista)

In [13]:
type(arr)

numpy.ndarray

In [16]:
matriz =[[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr[1]

2

In [20]:
arr[0] + arr[5]

7

In [23]:
matriz[2,1]

8

In [24]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arr[0:5]

array([1, 2, 3, 4, 5])

In [27]:
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [29]:
arr[: :3]

array([1, 4, 7])

In [31]:
arr[-3:]


array([7, 8, 9])

In [32]:
matriz


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
matriz[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [34]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])